//
//  HomeInteractor.swift
//  BitcoinApp
//
//  Created OSX on 15/08/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Luis Angel FR
//

import UIKit

class HomeInteractor: NSObject, URLSessionDelegate, URLSessionDataDelegate {
    //MARK: - Protocol Properties
    weak var presenter: HomePresenterProtocol?
    private var dataTask : URLSessionDataTask?
        private var responseData : Data = Data()
        private var httpResponse : HTTPURLResponse?
}

//MARK: - Interactor Methods
extension HomeInteractor: HomeInteractorProtocol {
    func getInitData() {
        
            let urlString = "https://api.coincap.io/v2/assets"
            if let url = URL(string: urlString) {
                if let data = try? Data(contentsOf: url){
                    let decodificador = JSONDecoder()
                    if let datosDecodificados = try? decodificador.decode(btcModelo.self, from: data){
                        print("Datos decodificados:::::: \(datosDecodificados.data)")
                        presenter?.info(datos: datosDecodificados.data)
                }
            }
        }
        
    }
    
}







