//
//  HomeProtocols.swift
//  BitcoinApp
//
//  Created OSX on 15/08/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Luis Angel FR
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: AnyObject {
    func nextView()
}
//MARK: Presenter -
protocol HomePresenterProtocol: AnyObject {
    func info(datos: [btcDetail])
    func getInitData()
    func nextView()
}

//MARK: Interactor -
protocol HomeInteractorProtocol: AnyObject {

  var presenter: HomePresenterProtocol?  { get set }
    func getInitData()
   
}

//MARK: View -
protocol HomeViewProtocol: AnyObject {
    func info(datos: [btcDetail])
  var presenter: HomePresenterProtocol?  { get set }
}
