//
//  HomePresenter.swift
//  BitcoinApp
//
//  Created OSX on 15/08/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Luis Angel FR
//

import UIKit

class HomePresenter {
    //MARK: - Protocol Properties
    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorProtocol?
    private let router: HomeWireframeProtocol

    //MARK: - Life Cycle
    init(interface: HomeViewProtocol, interactor: HomeInteractorProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension HomePresenter: HomePresenterProtocol {
    func nextView() {
        router.nextView()
    }
    

    
 
    func info(datos: [btcDetail]) {
        view?.info(datos: datos)
        print("los datos ya estan en el presenter:::: \(datos)")
    }
    
    
    func getInitData() {
        interactor?.getInitData()
    }

}

//MARK: - Private functions
extension HomePresenter {

}
