//
//  FavoriteProtocols.swift
//  BitcoinApp
//
//  Created OSX on 20/08/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Luis Angel FR
//

import Foundation

//MARK: Wireframe -
protocol FavoriteWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol FavoritePresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol FavoriteInteractorProtocol: AnyObject {

  var presenter: FavoritePresenterProtocol?  { get set }
}

//MARK: View -
protocol FavoriteViewProtocol: AnyObject {

  var presenter: FavoritePresenterProtocol?  { get set }
}
