//
//  FavoriteRouter.swift
//  BitcoinApp
//
//  Created OSX on 20/08/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Luis Angel FR
//

import UIKit

class FavoriteRouter {
    //MARK: - Protocol Properties
    weak var viewController: UIViewController?
    
    //MARK: - Static Methods
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = FavoriteViewController(nibName: nil, bundle: nil)
        let interactor = FavoriteInteractor()
        let router = FavoriteRouter()
        let presenter = FavoritePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}

//MARK: - Router Metods
extension FavoriteRouter: FavoriteWireframeProtocol {
    
}

//MARK: - Private functions
extension FavoriteRouter {
    
}
