//
//  FavoriteInteractor.swift
//  BitcoinApp
//
//  Created OSX on 20/08/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Luis Angel FR
//

import UIKit

class FavoriteInteractor {
    //MARK: - Protocol Properties
    weak var presenter: FavoritePresenterProtocol?
}

//MARK: - Interactor Methods
extension FavoriteInteractor: FavoriteInteractorProtocol {
    
}
